### ISSUE TITLE
Unexpected key 'ETag' found in params

### ISSUE THREAD

**Issue by tonyghita** [izaakschroeder/s3-streams#8]
The following code
```javascript
var S3 = require('aws-sdk').S3
var S3S = require('s3-streams')

var zlib = require('zlib')

var compress = zlib.createGzip()

var upload = S3S.WriteStream(new S3(), {
  Bucket: 'my-bucket',
  Key: 'my-key'
})

// readStream is a multipart file upload
readStream.pipe(compress).pipe(upload)
```

throws the error:

```
"err": {
    "message": "Unexpected key 'ETag' found in params",
    "name": "UnexpectedParameter",
    "stack": "UnexpectedParameter: Unexpected key 'ETag' found in params
                at fail (my-application/node_modules/aws-sdk/lib/param_validator.js:115:37)
                at validateStructure (my-application/node_modules/aws-sdk/lib/param_validator.js:50:14)
                at validateMember (my-application/node_modules/aws-sdk/lib/param_validator.js:61:21)
                at validate (my-application/node_modules/aws-sdk/lib/param_validator.js:9:10)
                at Request.VALIDATE_PARAMETERS (my-application/node_modules/aws-sdk/lib/event_listeners.js:88:32)
                at Request.callListeners (my-application/node_modules/aws-sdk/lib/sequential_executor.js:100:18)
                at callNextListener (my-application/node_modules/aws-sdk/lib/sequential_executor.js:90:14)
                at my-application/node_modules/aws-sdk/lib/event_listeners.js:75:9
                at finish (my-application/node_modules/aws-sdk/lib/config.js:228:7)
                at my-application/node_modules/aws-sdk/lib/config.js:244:9
                at SharedIniFileCredentials.get (my-application/node_modules/aws-sdk/lib/credentials.js:126:7)
                at getAsyncCredentials (my-application/node_modules/aws-sdk/lib/config.js:238:24)
                at Config.getCredentials (my-application/node_modules/aws-sdk/lib/config.js:258:9)
                at Request.VALIDATE_CREDENTIALS (my-application/node_modules/aws-sdk/lib/event_listeners.js:70:26)
                at Request.callListeners (my-application/node_modules/aws-sdk/lib/sequential_executor.js:97:18)
                at Request.emit (my-application/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
                at Request.emit (my-application/node_modules/aws-sdk/lib/request.js:604:14)
                at Request.transition (my-application/node_modules/aws-sdk/lib/request.js:21:12)
                at AcceptorStateMachine.runTo (my-application/node_modules/aws-sdk/lib/state_machine.js:14:12)
                at Request.runTo (my-application/node_modules/aws-sdk/lib/request.js:369:15)
                at Request.send (my-application/node_modules/aws-sdk/lib/request.js:353:10)
                at makeRequest (my-application/node_modules/aws-sdk/lib/service.js:169:27)
                at svc.(anonymous function) [as completeMultipartUpload] (my-application/node_modules/aws-sdk/lib/service.js:402:21)
                at multipartPromise (my-application/node_modules/s3-streams/lib/multipart.js:149:13)
                at tryCatcher (my-application/node_modules/s3-streams/node_modules/bluebird/js/main/util.js:24:31)
                at Promise._resolveFromResolver (my-application/node_modules/s3-streams/node_modules/bluebird/js/main/promise.js:427:31)
                at new Promise (my-application/node_modules/s3-streams/node_modules/bluebird/js/main/promise.js:53:37)
                at afterParts (my-application/node_modules/s3-streams/lib/multipart.js:148:11)
                at tryCatcher (my-application/node_modules/s3-streams/node_modules/bluebird/js/main/util.js:24:31)
                at Promise._settlePromiseFromHandler (my-application/node_modules/s3-streams/node_modules/bluebird/js/main/promise.js:454:31)
                at Promise._settlePromiseAt (my-application/node_modules/s3-streams/node_modules/bluebird/js/main/promise.js:530:18)
                at Promise._settlePromiseAtPostResolution (my-application/node_modules/s3-streams/node_modules/bluebird/js/main/promise.js:224:10)
                at Async._drainQueue (my-application/node_modules/s3-streams/node_modules/bluebird/js/main/async.js:182:12)
                at Async._drainQueues (my-application/node_modules/s3-streams/node_modules/bluebird/js/main/async.js:187:10)
                at Async.drainQueues (my-application/node_modules/s3-streams/node_modules/bluebird/js/main/async.js:15:14)
                at process._tickDomainCallback (node.js:492:13)",
    "code": "UnexpectedParameter"
  }
```

`aws-sdk` is at     
```
"aws-sdk": "^2.1.29"
```

**Comment by tonyghita** [comment]
I tried reverting to `"aws-sdk": "2.1.18"`, but still receive the same error.

**Comment by tonyghita** [comment]
Just got the same behavior running `examples/upload.js`

```
$ node ./example/upload.js --bucket=my-s3-bucket example/upload.js
Uploading 694 bytes.
Unable to upload file: { [UnexpectedParameter: Unexpected key 'ETag' found in params]
  message: 'Unexpected key \'ETag\' found in params',
  code: 'UnexpectedParameter',
  time: Fri May 29 2015 11:27:24 GMT-0700 (PDT) }
```

**Comment by izaakschroeder** [comment]
Resolved in https://github.com/izaakschroeder/s3-streams/pull/10
